name: CI
run-name: Running CI jobs 🚀
on: [push]
jobs:
  library:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: library tests
        run: |
          bash IBM-TSS/scripts/testLib.sh
      - name: binance ECDSA
        run: |
          bash IBM-TSS/scripts/testBinanceECDSA.sh
      - name: binance EDDSA
        run: |
          bash IBM-TSS/scripts/testBinanceEDDSA.sh
      - name: integration tests
        run: |
          bash IBM-TSS/scripts/testIntegration.sh

